# Generated by Django 5.1.7 on 2025-03-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
