# Generated by Django 5.1.7 on 2025-03-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('contact', models.PositiveIntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('book_published', models.DateTimeField()),
                ('bio', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
    ]
