# Generated by Django 5.1.7 on 2025-03-31 04:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_contact'),
        ('book', '0002_alter_book_isbn'),
        ('publication', '0001_initial'),
        ('reviews', '0001_initial'),
        ('volume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.publication'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.reviews'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcopy', 'Hardcopy'), ('pdf', 'Pdf')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='vol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volume.volume'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
    ]
