# Generated by Django 5.1.7 on 2025-04-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_title_book_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=25, null=True, unique=True),
        ),
    ]
